### ISSUE TITLE
use docker-compose has problem,it does‘t work.

### ISSUE THREAD

**Issue by zjp007** [paul-sama/splatoon3-bot#9]
How can i build my own splatoon3-bot for TG, i try docker, but it can't work. First, I edit `token` from `.env.sample`, then using commands `docker-compose up -d`. From logs it seems like open the http:1270.0.0.1:8080 url, I active but get none.

**Comment by paul-sama** [comment]
docker 没有试过
按以下步骤试试

python -m pip install --user pipx
python -m pipx ensurepath
pipx install nb-cli
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
cp .env.sample .env
edit .env
nb run --reload
